version: '3.8'

services:
  marzban:
    build: .
    container_name: marzban
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/var/lib/marzban
      - ./xray_config.json:/code/xray_config.json:ro
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
