mode: Global
port: 7890

{{ conf | except("proxy-groups", "port", "mode") | yaml }}

proxy-groups:
- name: '♻️ Automatic'
  type: load-balance
  strategy: round-robin
  proxies:
  {{ proxy_remarks | yaml | indent(2) }}
{{ conf.get("proxy-groups", []) | yaml }}
