"""add groups table

Revision ID: 02723eca82a4
Revises: 2b231de97dc3
Create Date: 2024-12-19 08:23:23.877421

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '02723eca82a4'
down_revision = '2b231de97dc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('inbounds_groups_association',
                    sa.Column('inbound_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['inbound_id'], ['inbounds.id'], ),
                    sa.PrimaryKeyConstraint('inbound_id', 'group_id')
                    )
    op.create_table('template_group_association',
                    sa.Column('user_template_id', sa.Integer(), nullable=True),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['user_template_id'], ['user_templates.id'], )
                    )
    op.create_table('users_groups_association',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('groups_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['groups_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'groups_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_groups_association')
    op.drop_table('template_group_association')
    op.drop_table('inbounds_groups_association')
    op.drop_table('groups')
    # ### end Alembic commands ###
