"""user_last_status_change

Revision ID: 07f9bbb3db4e
Revises: ccbf9d322ae3
Create Date: 2024-04-23 09:57:24.697613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f9bbb3db4e'
down_revision = 'ccbf9d322ae3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_status_change', sa.DateTime(), nullable=True))
    # Set last_status_change to migration time
    op.execute("UPDATE users SET last_status_change=CURRENT_TIMESTAMP WHERE last_status_change IS NULL")
    # NOTE: Due to sqlite limitations, the server_default can't be set to `now()`
    # NOTE: Due to sqlite limitations, last_status_change can't be altered to `NOT NULL`
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_status_change')
    # ### end Alembic commands ###
