"""Add auto_reset_usage field to User model

Revision ID: 1d4e027a21c3
Revises: 21226bc711ac
Create Date: 2024-11-06 19:04:18.656369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4e027a21c3'
down_revision = '21226bc711ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auto_reset_usage', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_reset_usage')
    # ### end Alembic commands ###
