"""admin discord id

Revision ID: 81554fa3c345
Revises: ac26f36783a2
Create Date: 2025-04-18 17:42:53.157022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81554fa3c345'
down_revision = 'ac26f36783a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('discord_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'discord_id')
    # ### end Alembic commands ###
