"""next plan to template relation

Revision ID: 959fb8e65fc3
Revises: 7a93bcd44713
Create Date: 2025-01-11 21:55:04.448613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959fb8e65fc3'
down_revision = '7a93bcd44713'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'next_plans', 'user_templates', ['user_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'next_plans', type_='foreignkey')
    # ### end Alembic commands ###
