"""add ech_config_list to hosts

Revision ID: 9fa4831e991a
Revises: e422f859847f
Create Date: 2025-07-29 13:11:02.048475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa4831e991a'
down_revision = 'e422f859847f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('ech_config_list', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'ech_config_list')
    # ### end Alembic commands ###
