"""Add allow in secure and disable host

Revision ID: a0715c2615f0
Revises: 1cf7d159fdbb
Create Date: 2023-09-13 20:39:58.913256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0715c2615f0'
down_revision = '1cf7d159fdbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('allowinsecure', sa.Boolean(), nullable=True))
    op.add_column('hosts', sa.Column('is_disabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'is_disabled')
    op.drop_column('hosts', 'allowinsecure')
    # ### end Alembic commands ###