"""Change data type to BigInteger

Revision ID: c314e7085d19
Revises: 0f720f5c54dd
Create Date: 2023-10-30 19:19:31.272361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c314e7085d19'
down_revision = '0f720f5c54dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_templates', sa.Column('data_limit_new', sa.BigInteger()))
    op.add_column('user_templates', sa.Column('expire_duration_new', sa.BigInteger()))
    conn = op.get_bind()
    conn.execute('UPDATE user_templates SET data_limit_new = CAST(data_limit AS BIGINT)')
    conn.execute('UPDATE user_templates SET expire_duration_new = CAST(expire_duration AS BIGINT)')
    op.drop_column('user_templates', 'data_limit')
    op.drop_column('user_templates', 'expire_duration')
    op.alter_column('user_templates', 'data_limit_new', new_column_name='data_limit')
    op.alter_column('user_templates', 'expire_duration_new', new_column_name='expire_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
