"""add last update

Revision ID: c4002d403273
Revises: c47250b790eb
Create Date: 2023-08-03 12:53:02.272814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4002d403273'
down_revision = 'c47250b790eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_update')
    # ### end Alembic commands ###
