"""User Log

Revision ID: d12f575d73b5
Revises: 77c86a261126
Create Date: 2023-09-30 18:11:27.910677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12f575d73b5'
down_revision = '77c86a261126'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('admin_username', sa.String(length=34), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=34), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_admin_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.Enum('active', 'disabled', 'limited', 'expired', name='userstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('active', 'disabled', 'limited', 'expired', name='userstatus'), nullable=True),
    sa.Column('old_data_limit', sa.BigInteger(), nullable=True),
    sa.Column('new_data_limit', sa.BigInteger(), nullable=True),
    sa.Column('data_limit_reset_strategy', sa.Enum('no_reset', 'day', 'week', 'month', 'year', name='userdatalimitresetstrategy'), nullable=False),
    sa.Column('used_traffic', sa.BigInteger(), nullable=True),
    sa.Column('old_expire', sa.Integer(), nullable=True),
    sa.Column('new_expire', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('create', 'modify', 'reset', 'remove', 'revoke', 'status_change', name='action'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_admin_id'], ['users.admin_id'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_at', 'admin_id', 'user_id')
    )
    op.create_index(op.f('ix_user_logs_id'), 'user_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_logs_id'), table_name='user_logs')
    op.drop_table('user_logs')
    # ### end Alembic commands ###
