"""Node Public Name

Revision ID: dbf0e9325f28
Revises: e56f1c781e46
Create Date: 2023-10-01 05:42:47.941228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf0e9325f28'
down_revision = 'e56f1c781e46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('public_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'public_name')
    # ### end Alembic commands ###
