"""add table node_admin_usages 

Revision ID: dee0fc70572a
Revises: 0976220c4786
Create Date: 2024-04-16 02:03:01.631209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee0fc70572a'
down_revision = '0976220c4786'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_admin_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('used_traffic', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_at', 'admin_id', 'node_id')
    )
    op.create_index(op.f('ix_node_admin_usages_id'), 'node_admin_usages', ['id'], unique=False)



def downgrade() -> None:
    op.drop_index(op.f('ix_node_admin_usages_id'), table_name='node_admin_usages')
    op.drop_table('node_admin_usages')