"""refactor sub updated at

Revision ID: e422f859847f
Revises: 343ad7904b19
Create Date: 2025-07-21 13:09:02.770670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e422f859847f'
down_revision = '343ad7904b19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_subscription_updates_table = op.create_table('user_subscription_updates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('user_agent', sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Transfer data from users to user_subscription_updates
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    users_table = sa.Table('users', sa.MetaData(),
                           sa.Column('id', sa.Integer),
                           sa.Column('sub_updated_at', sa.DateTime(timezone=True)),
                           sa.Column('sub_last_user_agent', sa.String(length=512)))

    for user in session.query(users_table).filter(users_table.c.sub_updated_at.isnot(None)):
        session.execute(
            user_subscription_updates_table.insert().values(
                user_id=user.id,
                created_at=user.sub_updated_at,
                user_agent=user.sub_last_user_agent or "Unknown"
            )
        )
    session.commit()

    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column('sub_last_user_agent')
        batch_op.drop_column('sub_updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub_updated_at', sa.DATETIME(timezone=True), nullable=True))
    op.add_column('users', sa.Column('sub_last_user_agent', sa.VARCHAR(length=512), nullable=True))
    op.drop_table('user_subscription_updates')
    # ### end Alembic commands ###
