name: Build Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/dashboard/package-lock.json

      - name: Install dashboard dependencies
        working-directory: ./app/dashboard
        run: npm ci

      - name: Build dashboard
        working-directory: ./app/dashboard
        run: VITE_BASE_API=/api/ npm run build --if-present -- --outDir build --assetsDir statics

      - name: Create 404.html
        working-directory: ./app/dashboard
        run: cp ./build/index.html ./build/404.html

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Log in to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/dayanch437/marzban-1:latest
            ghcr.io/dayanch437/marzban-1:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
