name: Code Format Checker
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff Format
      run: |
        ruff format --check .
